### ISSUE TITLE
Does Martin docker compose service support "env_file" property?

### ISSUE THREAD

**Issue by geospatialweb** [urbica/martin#1023]
This does not work. Fails to find `.env` file in the `go` directory whereas the `postgres` service accepts the `- ./go/.env` path without fail. Seemingly the `.env` file has to also be present in the current directory `- .env` for this `martin` service to work without fail...

```
martin:
    container_name: martin
    image: ghcr.io/maplibre/martin:latest
    command: ["--config", "./config/martin.yml"]
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ./go/.env
    networks:
      - app-network
    ports:
      - "3000:3000"
    volumes:
      - ./mvt:/config:ro
```

Docker Compose output: `WARN[0000] The "POSTGRES_DSN" variable is not set. Defaulting to a blank string.` Used in the `./config/martin.yml` property `connection_string: $POSTGRES_DSN`.

Put another `.env` file in the current directory containing `docker-compose.yml` and change `env_file` path to `- .env`... works.
