### ISSUE TITLE
Upgrade to RusTLS v0.22 (some breaking changes)

### ISSUE THREAD

**Issue by nyurik** [urbica/martin#1036]
Rustls crate has made a number of [breaking changes](https://github.com/rustls/rustls/releases/tag/v%2F0.22.0) in v0.22.  Most of them require reading documentation and seeing what rustls expects of their users now.

The new `Cargo.toml` would have these (and corresponding `.workspace=true` entries)

```toml
rustls = "0.22"
rustls-native-certs = "0.7"
rustls-pemfile = "2"
rustls-pki-types = { version = "1" }  # Probably needed
rustls-webpki = { version = "0.102" }  # Might be needed?
webpki-roots = { version = "0.26" }  # Might be needed?
```
