### ISSUE TITLE
Support SDF sprites

### ISSUE THREAD

**Issue by nyurik** [urbica/martin#1075]
In some cases, images should be encoded using SDF first.  The @flother's [spreet crate](https://github.com/flother/spreet) already supports it with https://github.com/flother/spreet/issues/58, so it should be fairly easy (?) to use that.

## Overview
Similar to the regular spritesheets, given a directory with png/svg/... images, converts all images in that directory and subdirectories to SDF images before packaging them in a spritesheet.  If needed SDF and non-SDF spritesheets can be combined by the client, e.g. `GET /sprites/icons,sdf_icons.png` (or `.json|@2x.png|@2x.json`.  No new API endpoints are introduced.

## CLI Configuration
```bash
martin --sdf-sprites <directory_or_image>
```

## YAML Configuration

```yaml
# Sprite configuration
sprites:
  # This controls how all all images will be processed. false by default
  # This can be overridden only by setting   sources.<sprite_id>.sdf
  default_sdf: false | true | pretransformed
  paths:
    # all SVG files in this dir will be published as a "my_images" sprite source
    - /path/to/my_images
  sources:
    # SVG images in this directory will be published as a "my_sprites" sprite source
    my_sprites: /path/to/some_dir
    # SDF SVG images in this directory will be published as a "my_sprites" sprite source
    my_sprites:
      path: /path/to/some_sdf_dir
      # This tells Martin to handle images in some_sdf_dir as SDFs
      sdf: false | true | pretransformed
```
