### ISSUE TITLE
Martin panics at start due to Postgres pool issue

### ISSUE THREAD

**Issue by Volatus** [urbica/martin#1255]
Happens with the latest version with both the macOS binary and the Docker image.

```
[2024-03-15T15:05:49Z ERROR martin] Unable to get a Postgres connection from the pool develop: Error occurred while creating a new object: db error: FATAL: SCRAM channel binding check failed
thread '<unnamed>' panicked at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/thread/local.rs:246:26:
cannot access a Thread Local Storage value during or after destruction: AccessError
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: tokio::task::local::Shared::schedule
   4: tokio::runtime::task::waker::wake_by_val
   5: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
   6: std::sys::common::thread_local::fast_local::destroy_value
   7: std::sys::unix::thread_local_dtor::register_dtor::run_dtors
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
fatal runtime error: thread local panicked on drop
zsh: abort      RUST_BACKTRACE=1 martin -c config.yml
```

The config is this, with values obfuscated
```yaml
# Connection keep alive timeout [default: 75]
keep_alive: 75
listen_addresses: "0.0.0.0:3000"

postgres:
  connection_string: "postgresql://user:password@host:port/dbname?sslmode=require"
  default_srid: 4326
  auto_bounds: calc

  tables:
    cities:
      layer_id: cities
      schema: public
      table: some_materialized_view
      srid: 4326
      geometry_column: center_point
      id_column: id
      minzoom: 0
      maxzoom: 30
      bounds: [-180.0, -90.0, 180.0, 90.0]
      extent: 4096
      buffer: 64
      clip_geom: true
      geometry_type: GEOMETRY
      properties:
        id: integer
        z: double precision
        n: character varying

    timezones:
      layer_id: timezones
      schema: public
      table: timezones
      srid: 4326
      geometry_column: geom
      id_column: gid
      minzoom: 0
      maxzoom: 30
      bounds: [-180.0, -90.0, 180.0, 90.0]
      extent: 4096
      buffer: 64
      clip_geom: true
      geometry_type: GEOMETRY
      properties:
        gid: int4
        tzid: varchar

  functions:
    some_layer:
      layer_id: some_layer
      schema: public
      function: some_func_name
      minzoom: 0
      maxzoom: 30
      bounds: [-180.0, -90.0, 180.0, 90.0]

    some_layer:
      layer_id: some_layer
      schema: public
      function: some_func_name
      minzoom: 0
      maxzoom: 30
      bounds: [-180.0, -90.0, 180.0, 90.0]
```
