### ISSUE TITLE
HowTo Provide Multiple PG Connections in Config

### ISSUE THREAD

**Issue by michaelmink** [urbica/martin#1289]
Hey, that is probably a quick one: I have the requirement on my side to handle table source from multiple db connections. 

Is this supported? If yes, then how can I add those into my config.yaml? And please add some hints in the example config file.

Thanks a lot in advance!

Michael

**Comment by sharkAndshark** [comment]
Hi @veschberwilli 
```yaml
keep_alive: 75

listen_addresses: '0.0.0.0:3000'

worker_processes: 8

cache_size_mb: 8
# Database configuration. This can also be a list of PG configs.
postgres:
  - connection_string:  postgres://postgres:postgres@localhost:5411/db
    default_srid: 4326
  - connection_string:  postgres://postgres:postgres@localhost:5422/db
    default_srid: 4326
```
