### ISSUE TITLE
Tiles are not displayed

### ISSUE THREAD

**Issue by pcace** [urbica/martin#1296]
Hi there, i am trying to get martin to provide tiles to be displayed in a react-map-gl application ( mapbox) 

this is what i do in the application: 

```typescript
<Source id="mySource" type="vector" url="http://0.0.0.0:3000/cityJsons">
        <Layer
          id="myLayer"
          type="line" // or "line", "symbol", "circle", "heatmap", "fill-extrusion", "raster", "hillshade" depending on your data and what you want to do
          source="mySource"
          source-layer="cityJsons"
          paint={{
            // add your paint styles here
            // for example:
            'line-color': '#888888',
            'line-opacity': 0.8,
          }}
        />
      </Source>
```

the tileset i am trying to use looks like this: 

http://0.0.0.0:3000/catalog
```json
{
  "tiles": {
    "cityJsons": {
      "content_type": "application/x-protobuf",
      "description": "cjdb.city_object.ground_geometry"
    }
  },
  "sprites": {

  },
  "fonts": {

  }
}
```
http://0.0.0.0:3000/cityJsons:
```json
{
  "tilejson": "3.0.0",
  "tiles": [
    "http://0.0.0.0:3000/cityJsons/{z}/{x}/{y}"
  ],
  "vector_layers": [
    {
      "id": "cityJsons",
      "fields": {
        "attributes": "jsonb",
        "cj_metadata_id": "integer",
        "geometry": "jsonb",
        "object_id": "varchar",
        "type": "varchar"
      }
    }
  ],
  "bounds": [-180, -90, 180, 90],
  "description": "cjdb.city_object.ground_geometry",
  "maxzoom": 30,
  "minzoom": 0,
  "name": "cityJsons"
}
```
this is the martin config: 

```yaml

keep_alive: 75
listen_addresses: '0.0.0.0:3000'

base_path: /tiles
worker_processes: 8
cache_size_mb: 20000
preferred_encoding: brotli
postgres:
  connection_string: 'postgresql://postgres:postgrespw@localhost:5432/testcjdb'
  default_srid: 3857
  pool_size: 20
  max_feature_count: 100000
  auto_bounds: calc tables:
    cityJsons:
  
      layer_id: city_object 
      schema: cjdb 
      table: city_object 
      srid: 3857 
      geometry_column: ground_geometry 
      id_column: id 
      minzoom: 0 
      maxzoom: 30 
      bounds: [-180.0, -90.0, 180.0, 90.0] 
      extent: 4096 
      buffer: 64 
      clip_geom: true 
      geometry_type: MULTIPOLYGON 
      properties:
        object_id : varchar
        cj_metadata_id : integer
        attributes: jsonb
        type: varchar
        geometry : jsonb
  
```
  

Looking at the network tab and the console output of martin it does show that it downloads tiles correctly. but they are not shown in the map.

Since these tiles are compressed, i am wondering if i miss something in the configuration?
