### ISSUE TITLE
add property data to tile

### ISSUE THREAD

**Issue by pcace** [urbica/martin#1297]
Hi there, 

as far as i understand its possible to add property data to each tile like so: 

```yaml
      # List of columns, that should be encoded as tile properties (required)
      properties:
        object_id: varchar
        cj_metadata_id: integer
        attributes: jsonb
        type: varchar
        geometry: jsonb
        id : integer
```

when looking at the tile in a browser, it does not show the data as expected: 

![image](https://github.com/maplibre/martin/assets/1011875/9792a2c1-78bc-4ed2-8b59-300cf8920cfc)

shouldnt there be the data from each row? or is this not how its ment to be?

Thanks!
