### ISSUE TITLE
Unable to generate spritesheet

### ISSUE THREAD

**Issue by gkinsman** [urbica/martin#1336]
Hi there!

Kicking the tyres on this as an alternative to tileserver-gl-light and was pretty quick to get going which was great!

I'm having some issues getting sprites working, though my config is pretty simple:

```yaml
# Publish MBTiles files
mbtiles:
  sources:
    # named source matching source name to a single file
    greater-london: ../tiles/London/greater-london.mbtiles

# Sprite configuration
sprites:
  paths:
    - ./osm-liberty

```

Tiles load fine with this config, but attempts to load sprites cause this error in the martin console:

```
[2024-05-11T21:34:26Z ERROR martin::srv::server] Unable to generate spritesheet
```
when trying to navigate to `http://localhost:3000/sprite/osm-liberty.json`

I found where this happens in the source code [here](https://github.com/maplibre/martin/blob/01c165c368841403a75fd885a8a010130d6456ab/martin/src/sprites/mod.rs#L216) but there don't appear to be logs from spreet and no verbose mode.

Does anyone have any ideas what I might be doing wrong?
