### ISSUE TITLE
Features are being dropped randomly with no systematic order

### ISSUE THREAD

**Issue by Zia-** [urbica/martin#1455]
Hi there,

I'm new to Martin. I've been using Tippecanoe so far, and it offers some ways to control how features should be dropped if they exceed a certain limit per tile. I'm not able to control this in Martin. _Kindly look at the following two scenarios:_

_Slightly left view:_
![image](https://github.com/user-attachments/assets/04ea576f-eed6-4eb6-bfa4-883cc7d80970)
_Slightly right view:_
![image](https://github.com/user-attachments/assets/8f085a13-074d-4f62-921b-98d8af9fa90e)

Here, I'm simply panning slightly to my right and the big yellow cluster suddenly appears. 

Also, when I start zooming out it randomly drops all features from random locations giving an impression that there is nothing in there. I need to zoom in enough to make sure.

_Low Zoom:_
![image](https://github.com/user-attachments/assets/8b3cb7fd-515e-4037-ae20-87535ff33469)

_High Zoom:_
![image](https://github.com/user-attachments/assets/ecd97ef8-8245-4983-8d86-e4d799e38bc8)

I have made sure it's not network timing out while loading the tile. Below is what my config.yaml looks like, which I copied from https://maplibre.org/martin/config-file.html. Am I missing something? Any kind of help to make it performant while not loosing the impression of where the polygons are at various zoom levels and pans would be extremely helpful.

```
keep_alive: 75
listen_addresses: '0.0.0.0:3000'
base_path: /tiles
worker_processes: 3
cache_size_mb: 1024
preferred_encoding: gzip
web_ui: enableforall
postgres:
  connection_string: '<my connection string>'
  default_srid: 4326
  pool_size: 20
  max_feature_count: 1000
  auto_bounds: skip
  auto_publish:
    from_schemas:
      - public
    tables:
      source_id_format: 'table.{schema}.{table}.{column}'
      from_schemas: my_other_schema
      id_columns: feature_id
      clip_geom: false
      buffer: 64
      extent: 4096
    functions:
      source_id_format: '{schema}.{function}'
  tables:
    table_source_id:
      layer_id: id
      schema: public
      table: test_table
      srid: 4326
      geometry_column: geom
      id_column: ~
      minzoom: 0
      maxzoom: 10
      bounds: [ -180.0, -90.0, 180.0, 90.0 ]
      extent: 4096
      buffer: 64
      clip_geom: true
      geometry_type: GEOMETRY
```
