### ISSUE TITLE
/catalog doesn't load pg function; tables are working fine

### ISSUE THREAD

**Issue by Zia-** [urbica/martin#1473]
Hi there,

I'm struggling with loading a custom _pg function_ to view some random points. The table _public.randompoints_ has _geom_ geometry column. The _/catalog_ endpoint shows all tables nicely, however I was expecting _function_zxy_query_ as well to appear there. Directly hitting _/function_zxy_query_ endpoint says _Source function_zxy_query does not exist_

This is the function:

```
CREATE OR REPLACE
    FUNCTION function_zxy_query(z integer, x integer, y integer)
    RETURNS bytea AS $$
DECLARE
  mvt bytea;
BEGIN
  SELECT INTO mvt ST_AsMVT(tile, 'function_zxy_query', 4096, 'geom') FROM (
    SELECT
      ST_AsMVTGeom(
          ST_Transform(ST_CurveToLine(geom), 3857),
          ST_TileEnvelope(z, x, y),
          4096, 64, true) AS geom
    FROM public.randompoints
    WHERE geom && ST_Transform(ST_TileEnvelope(z, x, y), 4326)
  ) as tile WHERE geom IS NOT NULL;

  RETURN mvt;
END
$$ LANGUAGE plpgsql IMMUTABLE STRICT PARALLEL SAFE;
```

Exactly how it's defined [here](https://maplibre.org/martin/sources-pg-functions.html), except my table name ie _public.randompoints_

And below is what the _config.yaml_ looks like:

```
keep_alive: 75
listen_addresses: '0.0.0.0:3000'
base_path: /tiles
worker_processes: 3
cache_size_mb: 1024
preferred_encoding: gzip
web_ui: enableforall
postgres:
  - connection_string: '<conn_string>'
    default_srid: 4326
    pool_size: 20
    max_feature_count: 10000
    auto_bounds: skip
    auto_publish:
      from_schemas:
        - public
      tables:
        source_id_format: '{schema}.{table}.{column}'
    functions:
      function_source_id:
        schema: public
        function: function_zxy_query
        minzoom: 0
        maxzoom: 30
        bounds: [ -180.0, -90.0, 180.0, 90.0 ]
```

Would highly appreciate if someone can point me where things are broken. Thanks!
