### ISSUE TITLE
the auto_publish  config not work

### ISSUE THREAD

**Issue by ljh2057** [urbica/martin#1502]
this is my config
```yaml
auto_publish:
    from_schemas:
      - public
    functions:
      source_id_format: '{schema}.{function}'
```
then i create a function 

```sql
CREATE OR REPLACE
    FUNCTION f_agp(z integer, x integer, y integer)
    RETURNS bytea AS $$
DECLARE
  mvt bytea;
BEGIN
  SELECT INTO mvt ST_AsMVT(tile, 'f_agp', 4096, 'geom') FROM (
    SELECT
      ST_AsMVTGeom(
          ST_Transform(geometry, 3857),
          ST_TileEnvelope(z, x, y),
          4096, 64, true) AS geom,name,class,gnid,xzname
    FROM pdc_agp
    WHERE geometry&& ST_Transform(ST_TileEnvelope(z, x, y), 4490)
  ) as tile WHERE geom IS NOT NULL;
  RETURN mvt;
END
$$ LANGUAGE plpgsql IMMUTABLE STRICT PARALLEL SAFE;
```
However, i visit  /catalog did not take effect
