### ISSUE TITLE
Docker Compose entrypoint and command ignored

### ISSUE THREAD

**Issue by jt-helsinki** [urbica/martin#1554]
The martin docker compose setup is ignoring the `command` under the `martin` service. The output in the console is

```
martin-1            | [2024-10-26T18:51:27Z INFO  martin] Config file is not specified, auto-detecting sources
```

Further no output is written into the config directory. 

This command "should" be appended to the `ENTRYPOINT` specified in the martin docker file (`ENTRYPOINT ["/usr/local/bin/martin"] `)  as per the output from running
```bash
docker image history --no-trunc ghcr.io/maplibre/martin:latest
``` 

Alternatively, if I add the following to the `martin` service I am still given the same console output. 

`entrypoint: ["/usr/local/bin/martin", "--config", "/config/config.yaml"]`

-OR-

```yml
entrypoint:
   - "/usr/local/bin/martin"
   - "--config"
   - "/config/config1.yaml"
```      
      

Is this a bug with Docker or a bug with the Martin setup. It seems others are using this setup and it works ok. 

Running on a mac (os 14.6.1 on arm chip ) and docker version 27.2.0.

This is the docker-compose.yaml. 

```yml
name: osm-maps-martin
services:
  db-source-martin:
    build:
      context: .
      dockerfile: docker/Dockerfile.postgis
    volumes:
      - ./container-data/database-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file: ".env"
    environment:
      - POSTGRES_PORT
    restart: on-failure
    healthcheck:
      test: "PGPASSWORD=docker pg_isready -h 127.0.0.1 -U docker -d public"
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 1m
  martin:
    image: ghcr.io/maplibre/martin:latest
    command: ["--config", "/config/config.yaml"]
    volumes:
      - ./container-data/martin/config:/config
      - ./container-data/martin/tiles:/tiles
    ports:
      - 8080:3000
    env_file: ".env"
    environment:
      - DATABASE_URL=postgresql://docker:docker@db-source-martin/public
      - RUST_LOG=actix_web=info,martin=debug,tokio_postgres=debug
    restart: unless-stopped
    depends_on:
      - db-source-martin
```

If would be very nice to allow for the martin CLI args to be also placed into an .env file.
