### ISSUE TITLE
Serve styles

### ISSUE THREAD

**Issue by artyomb** [urbica/martin#1607]
Is it possible to configure support for serving static files or Mapbox-style JSON files using a configuration file?

```yaml
static:
 - /path/to/static_dir
```
or

```yaml
styles:
 - /path/to/styles_dir
```

Additionally, when serving Mapbox-style JSON files specifically, could the system automatically add related fonts, sprites, and sources to the file?

**Comment by CommanderStorm** [comment]
> when serving Mapbox-style JSON files specifically, could the system automatically add related fonts, sprites, and sources to the file?

This part is a bit unclear, what do you mean by this specifically?

And yes, adding styles would defintively be required to implement this feature:
- #978

**Comment by artyomb** [comment]
The following sections could be added automatically:

**mapbox_style.json**:
```json
...
"glyphs": ".../fonts/{fontstack}/{range}.pbf",
"sprite": ".../sprites",
...
"sources": [
    "source_name": {
      "type": "vector",
      "url": "/tiles/.../tiles.json"
    },
]

**Comment by CommanderStorm** [comment]
I don't think that this would work as you intended. We would need to
- (solvable) pick source_name dependent on the stlyes usage
- decide if the user wants sdf or regular sprites
- decide which vector/sprite source a user needs to display the map they want

In particular because of the last issue, we would need to do the wrong kind of magic. I.e. the kind which does unintended things easily and is hard to debug our users).
=> I think our users will be much less confused without automatically adding this information

**Comment by artyomb** [comment]
This feature could be optional. Styles are typically served as static files, but they may also support templating, such as:
```yaml
...
"glyphs": "{{ .Fonts }}",
"sprite": "{{ .SdfSprites.base }}",
...
"sources": [
  {{range .Sources}}
    "{{.Name}}": {
      "type": "vector",
      "url": "{{.TileJson}}"
    },
  {{end}}
]
```

**Comment by CommanderStorm** [comment]
Lets track the work needed to resolve this issue in #518 instead.

**Comment by nyurik** [comment]
I think we may need to focus on this issue rather than the more generic (and possibly less needed?) #518.

## Use cases

* Martin needs to update URLs in a style to point to other resources served by Martin depending on the requesting server (we already do that for tilejson).
* Martin needs to know which styles are available to enable server-side rendering
  * #978 
* Martin should make all available styles show up in Maputnik when we integrate it
* When running on a localhost, Martin could function as a style editor by integrating with Maputnik, and saving all changes to the disk (TBD)

## Config structure

```yaml
styles:
  paths:
    # scan this whole dir, matching all *.json files
    # Each found file name is published as a style with the same name
    - /dir-path
    # specific json file will be published as a style, using its name
    - /path/to/osmbright.json
  sources:
    # named styles match style name to a single file
     my-osm-bright: /path/to/my-osm-bright.json
```

## CLI

Similar to `--font` and `--sprite`, introduce `--style <path>` .  It will work the same as `paths: [...]` in the config above

## API

| URL | Description |
|---|---|
| `/styles/{styleID}` | Style JSON |
| `/styles/{styleID}/{z}/{x}/{y}.png` | Render tile as a PNG for the given location |
