### ISSUE TITLE
"schema was not found" in functions but in tables it does

### ISSUE THREAD

**Issue by AimbotNooby** [urbica/martin#1652]
Somehow martin says it can't find the schema "points" for the function `function_linestring`. But it exists and works for the tables. And also the function definitely exists inside of the schema.
Can you please help we with this error?

Errors:
```
Configured source points_table from table points.points_table with point column (POINT, SRID=4326)
Unable to configure source function_linestring because schema 'points' was not found.  Possible values are:
```

config.yaml
```
keep_alive: 75
listen_addresses: '0.0.0.0:3000'
base_path: /
worker_processes: 8
cache_size_mb: 1024
preferred_encoding: gzip
web_ui: enable-for-all

postgres:
  connection_string: 'postgresql://postgres:password@postgis:5432/gps_test'
  default_srid: 4326
  pool_size: 20
  max_feature_count: 1000
  auto_bounds: skip

  tables:
    points_table:
      layer_id: points_layer
      schema: points
      table: points_table
      srid: 4326
      geometry_column: point
      id_column: id
      minzoom: 0
      maxzoom: 30
      bounds: [ -180.0, -90.0, 180.0, 90.0 ]
      extent: 4096
      buffer: 64
      clip_geom: true
      geometry_type: POINT
      properties:
        user_id: int4
        altitude: float8
        time: int8

  functions:
    function_linestring:
      schema: points
      function: convert_points_to_linestring
      minzoom: 0
      maxzoom: 30
      bounds: [ -180.0, -90.0, 180.0, 90.0 ]
```
