### ISSUE TITLE
Martin serving multiple database connections

### ISSUE THREAD

**Issue by darrenpierre90** [urbica/martin#1684]
Hi, I'm attempting to use Martin to serve from multiple Postgres databases. To do that I'm trying to setup Martin config where we can set up various 2 but potentially more Postgres databases 

what have I tried so far? 

I've tried adding two connection strings and it seems the second connection string overwrites the first one.

I've put a connection string in an array, but that also doesn't work. 

in the Martin docs , it says 

> # Database configuration. This can also be a list of PG configs.

But confused about how to set it up . 

Any Help would be appreciative.

**Comment by CommanderStorm** [comment]
This might be badly documented or we might have a bug.

We mean this like here:

https://github.com/maplibre/martin/blob/2d3e4d0f37bab0409c37c3c49d611284d5758526/martin/src/pg/config.rs#L196-L198

=> a list of `postgres`-configurations, not a list of `connection_string`s

Could you recheck if you have 2 configs? 

If the issue is what I think it is, how would you have understood the docs how We meant it:
Would the following be better
```yaml
# Database configuration.
# 
# This can also be a list of postgres configurations (i.e. a list of the dicutionary shown below)
```

**Comment by darrenpierre90** [comment]
<img width="1387" alt="Image" src="https://github.com/user-attachments/assets/497aa6e2-6ff4-4e6c-bb65-d03dff2367e2" />

I've also tried that variant and I got the following error : 
<img width="1432" alt="Image" src="https://github.com/user-attachments/assets/13bb006e-5bd7-470c-815f-614405757098" />

**Comment by darrenpierre90** [comment]
I think if there was just an example shown , it would make the documentation better

**Comment by nyurik** [comment]
this is not valid yaml.

```yaml
listen_addresses: '0.0.0.0:3000'
postgres:
  - connection_string: 'postgresql://server1'
    default_srid: 4326
    auto_bounds: skip
  - connection_string: 'postgresql://server2'
    default_srid: 4326
    auto_bounds: skip
```
