### ISSUE TITLE
GeoParquet backend

### ISSUE THREAD

**Issue by nicokant** [urbica/martin#1693]
Would be great if it was possible to serve tiles based on a geoparquet file.

This could be implemented for example using duckdb with the spatial extension, which has ST_ (almost) compatible functions.

**Comment by CommanderStorm** [comment]
[spec](https://geoparquet.org/releases/v1.1.0/)

Geoparquet does not have the concept of levels..

Therefore the best we could do is send out a 2d index into the geoparquet..
I am a bit unsure if this is desirable..

As far as I rememeber what it does have is lightweight indexes allowing to not read the entire file for a query.
Since there is no guarantee on sorting though.. this might be not be effective at all leading to an entire table-scan for quite simple operations..

For good performance, support for [geoparquet](https://geoparquet.org/) sources like [Overture Maps](https://docs.overturemaps.org/) does need a tile generation step like https://github.com/onthegomap/planetiler

Unsure if adding it makes sense..
What would you like to achive? Would simple 2d slicing suffice or would you require simplification at higher zoom levels?

**Comment by CommanderStorm** [comment]
relevant link

- https://github.com/duckdb/duckdb-spatial/issues/241

@nicokant @frafra I am a bit unsure if this makes sense to support.
Could you give more context on your usecase?

> For good performance, support for [geoparquet](https://geoparquet.org/) sources like [Overture Maps](https://docs.overturemaps.org/) does need a tile generation step like https://github.com/onthegomap/planetiler 
>
> Unsure if adding it makes sense..
What would you like to achive? Would simple 2d slicing suffice or would you require simplification at higher zoom levels?

**Comment by mbelt** [comment]
I'm have a PoC for this feature and early results are encouraging. I will push it after I get some time to clean it up a bit.

Using [geoarrow-rs](https://github.com/geoarrow/geoarrow-rs), tile request generate a geoparquet reader with a bbox equal to tile bounds. For well sorted geoparquet files, like what Overture Maps publishes, performance is comparable to Martin with PostGIS backend. 

It does require "covering" column metadata to be present in the geoparquet, technically it's optional. 

There is some work remaining before I'd call it solid:

- Mitigate huge tiles at low zoom level, it should have a way for the Martin user to configure filters beyond bounding box.
   Simple mitigations like "max feature count" work, but visually appear broken. 
- Make sure it supports geoparquet with non-native geometry column. (WKB)
- Configure which non-geometry columns are included in the tile.
- Configurable tile extent.
- Make sure logic for finding "covering" keys is correct according to the geoparquet spec.

**Comment by giswqs** [comment]
This would be a very nice feature! Very much looking forward to it.

**Comment by CommanderStorm** [comment]
Please remember that a feature request does not mean that it gets implemented. We are all volunteers, so this would depend on volunteer work.

**Comment by nyurik** [comment]
I think this is also blocked on
- #2054

**Comment by sdf-jkl** [comment]
@mbelt Hey, do you need assistance with this?

**Comment by mbelt** [comment]
@sdf-jkl Thanks for the reminder, I think I can have a draft PR open later this week.

**Comment by mbelt** [comment]
Update: Getting close. 

**Loading:** Single-file and glob path, local files and s3, but not az. 

**Encoding:** WKB and native encoding, all geometry types working.

**Property configuration**
`allowed_properties: ["osm_id", "highway"] `
or
`allowed_properties: ["!other_tags"]`
or 
`allowed_properties: []` to discard all. 

**Zoom Levels**
Simple `min_zoom` and `max_zoom` per source.
Experimenting with `min_zoom_level_column_name` and `max_zoom_level_column_name`, which is a hack, but it gets the job done for low zoom levels. Open to suggestions for alternative methods here. I don't want to go down the slippery slope of full blown tile recipes because that's not currently something martin is concerned with. 

**Tile Parameters**
`tile_extent` is configurable. 
`max_features_per_tile` is configurable, but implementation is still not optimal for rendering. Haven't really dug in yet, but if anyone familiar with arrow stuff knows how to get `ArrowReaderBuilder<AsyncReader<...>>.with_limit(num_features)` to pick the row groups it enumerates randomly, I would like to know about it. Otherwise I can filter further into the enumeration, but l guess it will be less efficient. 

**TODO**

- [x] Debug a discontinuity between tiles that only shows up in some tests. 
- [x] Debug a couple overture water features that get corrupted. Generally, large polygon cropping seems to be working fine. 
- [x] Revisit serialization of complex arrow types, right now they aren't aligned with style expressions can parse. 
- [ ] Planar->spherical edge conversion. 
- [ ] Reprojection of non WGS84. 


```
    overturebldg:
      max_features_per_tile: 100000
      path: s3://overturemaps-us-west-2/release/2025-10-22.0/theme=buildings/type=building/*.parquet
      min_zoom: 9
      max_zoom: 11
    overtureinfra:
      max_features_per_tile: 100000
      path: s3://overturemaps-us-west-2/release/2025-10-22.0/theme=base/type=infrastructure/*.parquet
      min_zoom: 10
      max_zoom: 10
    overtureland:
      max_features_per_tile: 100000
      path: s3://overturemaps-us-west-2/release/2025-10-22.0/theme=base/type=land/*.parquet
      min_zoom: 2
    overturewater:
      max_features_per_tile: 100000
      path: s3://overturemaps-us-west-2/release/2025-10-22.0/theme=base/type=water/*.parquet
      min_zoom: 5
    overtureplace:
      max_features_per_tile: 100000
      path: s3://overturemaps-us-west-2/release/2025-10-22.0/theme=places/type=place/*.parquet
      min_zoom: 8
      max_zoom: 10
```
<img width="1982" height="1252" alt="Image" src="https://github.com/user-attachments/assets/7fbd2b5a-1e45-4f41-97e7-17175b187adb" />

_I do not endorse rendering overture data straight from the creature like this, but it is possible._
