### ISSUE TITLE
Tiles get lost

### ISSUE THREAD

**Issue by panterlo** [urbica/martin#1694]
The video shows the issue (similar with fill, line etc). Source is Postgres.

https://github.com/user-attachments/assets/b689b4bc-441d-452f-8fb5-af81a86d0bc0

If I export to an MBTiles file with martin-cp same table and repoint MapLibre source to the MBTile served through Martin everything works but for some reason the source Postgres table get's this wierd issue.

**Comment by CommanderStorm** [comment]
Hmmm..
Are you maybe using an old postgres version?

- https://github.com/maplibre/martin/issues/1651

**Comment by panterlo** [comment]
I am using 
```
POSTGIS="3.5.2 dea6d0a" [EXTENSION] PGSQL="170" GEOS="3.12.1-CAPI-1.18.1" PROJ="9.4.0 NETWORK_ENABLED=OFF URL_ENDPOINT=https://cdn.proj.org USER_WRITABLE_DIRECTORY=/tmp/proj DATABASE_PATH=/usr/share/proj/proj.db" (compiled against PROJ 9.4.0) LIBXML="2.9.14" LIBJSON="0.17" LIBPROTOBUF="1.4.1" WAGYU="0.5.0 (Internal)"
```

**Comment by CommanderStorm** [comment]
Hmm.. so likely a differnt issue.

The line seems pretty thin.. could this be a styling/rendering issue?
Unlikely though given that martin-cp does solve your issue.

Is the data you are using maybe publicly avaliable somewhere? (can I debug on the same data?)

**Comment by CommanderStorm** [comment]
And are there any clues in the network console/ other indicators

**Comment by panterlo** [comment]
Nothing in the console, same also applies for fill / polygons.

https://github.com/user-attachments/assets/1e49cc0f-5275-46db-82e7-62c25a2464c6

 Let me publish our server so you can try out...

**Comment by CommanderStorm** [comment]
> Let me publish our server

I trust you that this is happening. Publishing said server is not something I nessesarily need ^^

question is what data you are running (maybe OSM?) and whether I can run a debug build agains said data.

**Comment by CommanderStorm** [comment]
Do you maybe have `max_feature_count` configured?

**Comment by panterlo** [comment]
oh... terrible.... yeah... I just copied the example and it had  max_feature_count: 1000

**Comment by panterlo** [comment]
```
postgres:
  - connection_string: 'postgresql://postgres:XXX@localhost:5432/lm_top10'
    default_srid: 4326
    pool_size: 20
    max_feature_count: 10000
    auto_bounds: skip
    auto_publish:
      tables:
        source_id_format: 'lm_top10.table.{schema}.{table}.{column}'
        id_columns: fid
        clip_geom: true
        buffer: 64
        extent: 4096
      functions:
        source_id_format: '{schema}.{function}'
```
