### ISSUE TITLE
Configure sqlfluff to auto-format SQL files

### ISSUE THREAD

**Issue by nyurik** [urbica/martin#1702]
Something like this should be added to the root `.pre-commit-config.yaml` file to configure [sqlfluff](https://docs.sqlfluff.com/en/stable/production/pre_commit.html).

This needs a more thorough configuration, e.g. maybe different spacing, alignment, capitalization, and other settings.  We might need to create a dedicated `.sqlfluff` file with all these settings.

```yaml
   - repo: https://github.com/sqlfluff/sqlfluff
     rev: 3.3.1
     hooks:
       - id: sqlfluff-fix
         name: sqlfluff-fix
         args: [ "--dialect", "postgres" ]
         files: '^.*\.sql$'
```
