### ISSUE TITLE
Optimize CI jobs to only run when needed

### ISSUE THREAD

**Issue by nyurik** [urbica/martin#1811]
It seems some projects use this style of a CI test to check if any job has failed or not, without explicitly waiting for them to pass/fail/be ignored.

```yaml
  ci-passed:
    if: always()
    needs:  [  <list of CI job names to check>  ]
    runs-on: ubuntu-latest
    steps:
      - if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}
        run: exit 1
```

I think we can use the same approach to simplify our CI to only run on relevant changes, while still making our CI ruleset to depend on this one job to tag the PR as passing.
