### ISSUE TITLE
Make COG web friendly

### ISSUE THREAD

**Issue by sharkAndshark** [urbica/martin#1820]
[WebMercatorQuad](https://docs.ogc.org/is/17-083r2/17-083r2.html#72) is the most popular tile grid. Almost all clients (maplibre, OL, Mapbox, etc) take it as default.

It would be better if martin could support it like:

## Configuration

```yml
cog:
  # default false. 
  # When enabled, martin would take the requested tile index(/{z}/{x}/{y}) as tile index of webmercatorquad, and martin will finish the clipping and warping internally.
  # It only works when the projection of COG file it's 3857
  web_friendly: true
```

## Tilejson

Martin would create a mapping between the inner custom tilegrid of cog file and the WebMercatorQuad.

The min/max zoom  would be updated then.

`/cog_source`

** **

```jsonc
{
//  "maxzoom": 3, Before web_friendly enabled
//  "minzoom": 0,  Before web_friendly enabled
 "maxzoom": 14,   // after web_friendly enabled
 "minzoom":  11,  // after web_friendly enabled
  "tilejson": "3.0.0",
  "tiles": [
    "http://localhost:3111/cog_source/{z}/{x}/{y}"
  ]
}
```

No any tilejson Compatibility got broken here and the most popular projection and tilegrid got supported then. 

[Titiler support WebMercatorQuad for COG either and even more custom tilegrid can be added](https://developmentseed.org/titiler/user_guide/tile_matrix_sets/), and its enpoint is flexible like `/cog/tiles/{tileMatrixSetId}/{z}/{x}/{y}[@{scale}x][.{format}]`, see https://developmentseed.org/titiler/endpoints/cog/#api
