### ISSUE TITLE
Container keeps restarting

### ISSUE THREAD

**Issue by 0rg3n** [urbica/martin#423]
Dear devs,

I have set up a small using docker-compose to see if martin plays nicely with our geodata. Pretty much like the example, just added traefik to it:

```yaml
version: '3.4'

networks:
  proxy:
    external: true
  intern:
    internal: true
    name: "martin_intern"

services:
  db:
    image: postgis/postgis:14-3.1-alpine
    hostname: postgis
    container_name: martin_postgis
    labels:
      autoheal: "true"
    volumes:
      - "/srv/docker/volumes/martin/db/data:/var/lib/postgresql/data"
      - "/srv/docker/volumes/martin/db/dump:/var/lib/postgresql/dump"
    networks:
      - intern
    expose:
      - 5432
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    restart: unless-stopped
    healthcheck:
      test: "exit 0"
    deploy:
      resources:
        limits:
          memory: "5G"

  martin:
    image: maplibre/martin
    hostname: martin
    container_name: martin_martin
    networks:
      - intern
      - proxy
    expose:
      - 3000
    environment:
      - DATABASE_URL=postgres://postgres@db/db
      - RUST_LOG=actix_web=info,martin=debug,tokio_postgres=debug
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.martin-web.entrypoints=web"
      - "traefik.http.routers.martin-web.rule=Host(`martin.my.host`)"
      - "traefik.http.middlewares.martin-web-redirect-web-secure.redirectscheme.scheme=https"
      - "traefik.http.routers.martin-web.middlewares=martin-web-redirect-web-secure"
      - "traefik.http.routers.martin.entrypoints=websecure"
      - "traefik.http.routers.martin.rule=Host(`martin.my.host`)" 
      - "traefik.http.services.martin.loadbalancer.server.port=3000"
    restart: unless-stopped
    depends_on:
      - db
```
Unfortunately, the container keeps on crashing. It seems to be unable to connect to the database. Here's the log output:

```
$ docker-compose logs -f martin
Attaching to martin_martin
martin_1  | [2022-09-30T11:26:55Z INFO  martin] Starting martin v1.0.0-alpha.0
martin_1  | [2022-09-30T11:26:55Z INFO  martin] Config is not set
martin_1  | [2022-09-30T11:26:55Z INFO  martin] Connecting to database
martin_1  | [2022-09-30T11:26:58Z INFO  martin] Starting martin v1.0.0-alpha.0
martin_1  | [2022-09-30T11:26:58Z INFO  martin] Config is not set
martin_1  | [2022-09-30T11:26:58Z INFO  martin] Connecting to database
martin_1  | [2022-09-30T11:27:01Z INFO  martin] Starting martin v1.0.0-alpha.0
martin_1  | [2022-09-30T11:27:01Z INFO  martin] Config is not set
martin_1  | [2022-09-30T11:27:01Z INFO  martin] Connecting to database
martin_1  | [2022-09-30T11:27:04Z INFO  martin] Starting martin v1.0.0-alpha.0
martin_1  | [2022-09-30T11:27:04Z INFO  martin] Config is not set
martin_1  | [2022-09-30T11:27:04Z INFO  martin] Connecting to database
martin_1  | [2022-09-30T11:27:07Z INFO  martin] Starting martin v1.0.0-alpha.0
martin_1  | [2022-09-30T11:27:07Z INFO  martin] Config is not set
martin_1  | [2022-09-30T11:27:07Z INFO  martin] Connecting to database
martin_1  | [2022-09-30T11:27:10Z INFO  martin] Starting martin v1.0.0-alpha.0
martin_1  | [2022-09-30T11:27:10Z INFO  martin] Config is not set
martin_1  | [2022-09-30T11:27:10Z INFO  martin] Connecting to database
martin_1  | [2022-09-30T11:27:15Z INFO  martin] Starting martin v1.0.0-alpha.0
martin_1  | [2022-09-30T11:27:15Z INFO  martin] Config is not set
martin_1  | [2022-09-30T11:27:15Z INFO  martin] Connecting to database
martin_1  | [2022-09-30T11:27:23Z INFO  martin] Starting martin v1.0.0-alpha.0
martin_1  | [2022-09-30T11:27:23Z INFO  martin] Config is not set
martin_1  | [2022-09-30T11:27:23Z INFO  martin] Connecting to database
martin_1  | [2022-09-30T11:27:37Z INFO  martin] Starting martin v1.0.0-alpha.0
martin_1  | [2022-09-30T11:27:37Z INFO  martin] Config is not set
martin_1  | [2022-09-30T11:27:37Z INFO  martin] Connecting to database
martin_martin exited with code 139
```

Any help would be much appreciated!
