### ISSUE TITLE
Setting docker-compose setting 'command' causes martin to try to parse itself as a config

### ISSUE THREAD

**Issue by gbip** [urbica/martin#499]
This docker-compose file causes martin to fail with the following error:

```
version: '3'

services:
  martin:
    image: maplibre/martin:v0.6.1
    restart: unless-stopped
    command : /usr/local/bin/martin
    environment:
      - DATABASE_URL=postgres://postgres:password@db/db
    depends_on:
      - db

  db:
    image: postgis/postgis:14-3.1-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - ./pg_data:/var/lib/postgresql/data
```
```
martin_bug-martin-1  | [2022-12-01T15:49:55Z INFO  martin] Starting Martin v0.6.1
martin_bug-martin-1  | [2022-12-01T15:49:55Z INFO  martin] Config file is not specified
martin_bug-martin-1  | [2022-12-01T15:49:55Z INFO  martin::pg::db] Connecting to database
martin_bug-martin-1  | [2022-12-01T15:49:55Z ERROR martin] Can't parse connection string /usr/local/bin/martin: invalid connection string: unexpected EOF
```

One might want to override the command to pass specific options as CLI arguments instead of config.
