### ISSUE TITLE
Caching with nginx not working/slow

### ISSUE THREAD

**Issue by eftas-gka** [urbica/martin#506]
Hello dear folks,

we are currently testing martin to render a network of cycle paths. Unfortunately even though we are using nginx to cache tile requests, it takes quite a long time (up to 20s) each time to render the network (even when switching off/on which should be covered by the cashing mechanism). Any ideas on how to debug this? Our setup is quite similiar to the example on the github page. In fact we are using the very same [nginx.conf](https://github.com/maplibre/martin/blob/main/nginx.conf).

```yaml
martin:
    image: maplibre/martin:main
    hostname: martin
    container_name: project_martin
    networks:
      - intern
    environment:
      - DATABASE_URL=postgres://martin:verysecretpassword@postgres/project
      - RUST_LOG=actix_web=info,martin=debug,tokio_postgres=debug
    restart: unless-stopped
    depends_on:
      - postgres

  nginx_martin:
    image: nginx:alpine
    hostname: martin_nginx
    container_name: project_martin_nginx
    volumes:
      - "./data/martin_nginx/cache:/var/cache/nginx"
      - "./data/martin_nginx/log:/var/log/nginx"
      - "./data/martin_nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
    networks:
      - intern
      - traefik
    labels:
      traefik.enable: "true"
      traefik.http.routers.project-nginxmartin-websecure.entrypoints: "websecure"
      traefik.http.routers.project-nginxmartin-websecure.rule: "Host(`maps.project.our.server`)"
      traefik.http.routers.project-nginxmartin-websecure.tls: true
      traefik.http.routers.project-nginxmartin-websecure.tls.certresolver: httpResolver
      traefik.http.services.project-nginxmartin-websecure.loadbalancer.server.port: 80
      traefik.docker.network: "traefik"
    restart: unless-stopped
    depends_on:
      - martin

```

Any help would be much appreciated!
