### ISSUE TITLE
Decide how to configure file-based sources like mbtiles and pmtiles

### ISSUE THREAD

**Issue by nyurik** [urbica/martin#513]
A tile source could be a file like `foo.pmtiles` or `bar.mbtiles` - both of which contain just one set of tiles. Moreover, at least mbtiles stores some metadata as well to make the creation of tilejson relatively easy.

We need a configuration schema that:
* publish a single file as a source, with the file name being the source ID
* same but publish a list of files
* publish a whole directory(s) of files, possibly with a glob pattern
* add some configuration params to a single file like `maxzoom`
* add some configuration params to all the files discovered in a directory(s)
* ideally it should looks relatively consistent with how postgres will be configured as part of #512

### ideas

```yaml
# Single file
pmtiles: /path/to/file.pmtiles

# Directory of files - will only look at *.pmtiles
pmtiles: /path/to/dir

# A few paths and a few source IDs
pmtiles:
  paths:
    - /dir-path
    - /path/to/pmtiles2.pmtiles
  sources:
      pm-src1: /tmp/pmtiles.pmtiles
      pm-src2:
        path: /tmp/pmtiles.pmtiles
        maxzoom: 10

# A map of source-IDs to individual files -- this method wouldn't handle multiple files though,
# or else it would need to ignore the ID if the path is a directory, which is not very clear to the users.
pmtiles:
    id1: /dir/path
    id2: /file.mbtiles
    id3:
        path: /foo/bar
        maxzoom: 10

# A list of objects (similar to PG), where each could be either a file or a dir.  A bit verbose to specify the ID
# CONs: possibly a bit less ergonomic because the ID must be specified explicitly, but at the same time
# if the file name is good enough as the ID, this is the cleanest approach.
pmtiles:
    - path: file.mbtiles
      id: foo
      maxzoom: 10
    - path: /path
      maxzoom: 11
```
