### ISSUE TITLE
Basic Example not works ?

### ISSUE THREAD

**Issue by CarlosZiegler** [urbica/martin#515]
Hey, 
I am tryng to understand how it works. I running the docker-compose and this running BUT dont works with my mapbox app.
I tried to catch some routes from DOC and not works:

<img width="937" alt="image" src="https://user-images.githubusercontent.com/38855507/207147187-7919c3ea-02f8-4442-97c2-2f93728c6aa3.png">

Only the `http://localhost:3000/index.json` route works fine and give me the result:
```json
{
	"public.points1.geom": {
		"id": "public.points1.geom",
		"schema": "public",
		"table": "points1",
		"srid": 4326,
		"geometry_column": "geom",
		"bounds": [
			-179.9561151226376,
			-89.98408467464485,
			179.9599738962007,
			89.99366560776792
		],
		"extent": 4096,
		"buffer": 64,
		"clip_geom": true,
		"geometry_type": "POINT",
		"properties": {
			"gid": "int4"
		}
	},
	"public.table_source_multiple_geom.geom1": {
		"id": "public.table_source_multiple_geom.geom1",
		"schema": "public",
		"table": "table_source_multiple_geom",
		"srid": 4326,
		"geometry_column": "geom1",
		"bounds": [
			-179.97959218559103,
			-89.97591631186795,
			179.97374386664868,
			89.97372708607783
		],
		"extent": 4096,
		"buffer": 64,
		"clip_geom": true,
		"geometry_type": "POINT",
		"properties": {
			"gid": "int4",
			"geom2": "geometry"
		}
	},
	"public.points1": {
		"id": "public.points1",
		"schema": "public",
		"table": "points1",
		"srid": 4326,
		"geometry_column": "geom",
		"bounds": [
			-179.9561151226376,
			-89.98408467464485,
			179.9599738962007,
			89.99366560776792
		],
		"extent": 4096,
		"buffer": 64,
		"clip_geom": true,
		"geometry_type": "POINT",
		"properties": {
			"gid": "int4"
		}
	},
	"public.table_source.geom": {
		"id": "public.table_source.geom",
		"schema": "public",
		"table": "table_source",
		"srid": 4326,
		"geometry_column": "geom",
		"bounds": [
			-2.0,
			-1.0,
			45.0,
			55.764475
		],
		"extent": 4096,
		"buffer": 64,
		"clip_geom": true,
		"geometry_type": "GEOMETRY",
		"properties": {
			"gid": "int4"
		}
	},
	"public.points2": {
		"id": "public.points2",
		"schema": "public",
		"table": "points2",
		"srid": 4326,
		"geometry_column": "geom",
		"bounds": [
			-179.96514970485015,
			-89.9899505519987,
			179.94494071254508,
			89.99430117230658
		],
		"extent": 4096,
		"buffer": 64,
		"clip_geom": true,
		"geometry_type": "POINT",
		"properties": {
			"gid": "int4"
		}
	},
	"public.points2.geom": {
		"id": "public.points2.geom",
		"schema": "public",
		"table": "points2",
		"srid": 4326,
		"geometry_column": "geom",
		"bounds": [
			-179.96514970485015,
			-89.9899505519987,
			179.94494071254508,
			89.99430117230658
		],
		"extent": 4096,
		"buffer": 64,
		"clip_geom": true,
		"geometry_type": "POINT",
		"properties": {
			"gid": "int4"
		}
	},
	"MixedCase.MixPoints": {
		"id": "MixedCase.MixPoints",
		"schema": "MixedCase",
		"table": "MixPoints",
		"srid": 4326,
		"geometry_column": "Geom",
		"extent": 4096,
		"buffer": 64,
		"clip_geom": true,
		"geometry_type": "POINT",
		"properties": {
			"Gid": "int4",
			"TABLE": "text"
		}
	},
	"MixedCase.MixPoints.Geom": {
		"id": "MixedCase.MixPoints.Geom",
		"schema": "MixedCase",
		"table": "MixPoints",
		"srid": 4326,
		"geometry_column": "Geom",
		"extent": 4096,
		"buffer": 64,
		"clip_geom": true,
		"geometry_type": "POINT",
		"properties": {
			"Gid": "int4",
			"TABLE": "text"
		}
	},
	"public.points3857.geom": {
		"id": "public.points3857.geom",
		"schema": "public",
		"table": "points3857",
		"srid": 3857,
		"geometry_column": "geom",
		"bounds": [
			-178.97411541086134,
			-88.99911795374842,
			178.98348024095648,
			88.99729682736901
		],
		"extent": 4096,
		"buffer": 64,
		"clip_geom": true,
		"geometry_type": "POINT",
		"properties": {
			"gid": "int4"
		}
	},
	"public.table_source": {
		"id": "public.table_source",
		"schema": "public",
		"table": "table_source",
		"srid": 4326,
		"geometry_column": "geom",
		"bounds": [
			-2.0,
			-1.0,
			45.0,
			55.764475
		],
		"extent": 4096,
		"buffer": 64,
		"clip_geom": true,
		"geometry_type": "GEOMETRY",
		"properties": {
			"gid": "int4"
		}
	},
	"public.points3857": {
		"id": "public.points3857",
		"schema": "public",
		"table": "points3857",
		"srid": 3857,
		"geometry_column": "geom",
		"bounds": [
			-178.97411541086134,
			-88.99911795374842,
			178.98348024095648,
			88.99729682736901
		],
		"extent": 4096,
		"buffer": 64,
		"clip_geom": true,
		"geometry_type": "POINT",
		"properties": {
			"gid": "int4"
		}
	},
	"public.table_source_multiple_geom": {
		"id": "public.table_source_multiple_geom",
		"schema": "public",
		"table": "table_source_multiple_geom",
		"srid": 4326,
		"geometry_column": "geom1",
		"bounds": [
			-179.97959218559103,
			-89.97591631186795,
			179.97374386664868,
			89.97372708607783
		],
		"extent": 4096,
		"buffer": 64,
		"clip_geom": true,
		"geometry_type": "POINT",
		"properties": {
			"gid": "int4",
			"geom2": "geometry"
		}
	},
	"public.table_source_multiple_geom.geom2": {
		"id": "public.table_source_multiple_geom.geom2",
		"schema": "public",
		"table": "table_source_multiple_geom",
		"srid": 4326,
		"geometry_column": "geom2",
		"bounds": [
			-179.97959218559103,
			-89.97591631186795,
			179.97374386664868,
			89.97372708607783
		],
		"extent": 4096,
		"buffer": 64,
		"clip_geom": true,
		"geometry_type": "POINT",
		"properties": {
			"geom1": "geometry",
			"gid": "int4"
		}
	}
}
```

I tried to add this source on mapbox:

```javascript
   map.addLayer({
        id: 'points',
        type: 'circle',
        source: {
          type: 'vector',
          url: 'http://localhost:3000/points1'
        },
        'source-layer': 'points1',
        paint: {
          'circle-color': 'red'
        }
      });
```
The routes `health` and `catalog` not found.

I did something wrong ? 

I am ussing this docker-compose:

```
version: "3"

services:
  martin:
    image: maplibre/martin
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://postgres@db/db
      - RUST_LOG=actix_web=info,martin=debug,tokio_postgres=debug
    depends_on:
      - db

  db:
    image: postgis/postgis:14-3.3-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      # POSTGRES_* variables are used by the postgis/postgres image
      # PG_* variables are used by psql
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
      - PGDATABASE=db
      - PGUSER=postgres
    volumes:
      - ./tests/fixtures:/fixtures
      - ./tests/fixtures/initdb-dc.sh:/docker-entrypoint-initdb.d/20_martin.sh

  db-legacy:
    image: postgis/postgis:11-3.0-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
      - PGDATABASE=db
      - PGUSER=postgres
    volumes:
      - ./tests/fixtures:/fixtures
      - ./tests/fixtures/initdb-dc.sh:/docker-entrypoint-initdb.d/20_martin.sh

```

I will to use it to provide some tiles from our map, now we are working with gcp but this will be best way to get tiles direct from DB.

thanks
