### ISSUE TITLE
Add support for static file serving

### ISSUE THREAD

**Issue by nyurik** [urbica/martin#518]
Static file serving is practically a requirement for a tile server - e.g. serve some simple javascript demo, some font files, etc.  Here's a proposed configuration:

```yaml
static:
  # All files in /path/to/foo will be available from the  /foo  URL.
  "foo": /path/to/foo

  # Map slash to the root, overriding default demo site if we ever build it
  "/": /path/to/root

  # Complete configuration of  /bar  URL
  "bar":
      path: /path/to/bar
      index_file: index.html    # if requesting /bar without a file, which file to serve
      # possibly other params (compression, content types, cors, ...) -- but lets keep it simple for now
```

### TBD
Naming:  We can also call it `static` or `content` or `files` or  ...?
Conflicts: If source ID conflicts with a source name, what takes precedence?
