### ISSUE TITLE
Invalid source name in readme

### ISSUE THREAD

**Issue by korywka** [urbica/martin#582]
Greetings.

I use config file without any `id_format` option my source name is `public.source_points.geometry`.
Which is `schema.table_name.column`.

But in readme we have:
`For [Table Sources](https://github.com/maplibre/martin#table-sources) it is {table_name} by default.`

That is not true, at least if running with config file.

**Comment by nyurik** [comment]
@korywka could you give an example of your config file?  I am not certain i understand the problem

**Comment by korywka** [comment]
@nyurik yep, it is pretty standard: 

```yaml
postgres:
  connection_string:
  default_srid: 4326

  tables:
    source_points:
      schema: public
      table: source_points
      srid: 3857
      geometry_column: geometry
      id_column: ~
      minzoom: 14
      maxzoom: 30
      properties:
        id: int4
        category: varchar
        property_type: varchar
        ppsf: float4
        rent_estimate: int4
        area_lot_sf: float4
        area_building: int4
        assessor_last_sale_date: date
        assessor_last_sale_amount: int4
        bedrooms_count: int4
        bath_count: float4
        year_joined: int4
        tax_assessed_value_total: int4
        tax_billed_amount: float4
        tax_exemption: varchar
        construction_type: varchar
        stories_count: int4
        status_owner_occupied_flag: int4
        pool: int4
        rooms_basement_area: int4
        parking_space_count: int4
    
    source_polygons:
      schema: public
      table: source_polygons
      srid: 3857
      geometry_column: geometry
      id_column: ~
      minzoom: 14
      maxzoom: 30
      properties:
        id: int4
        height: int4
        min_height: int4
        category: varchar
        property_type: varchar
        ppsf: float4
        rent_estimate: int4
        area_lot_sf: float4
        area_building: int4
        assessor_last_sale_date: date
        assessor_last_sale_amount: int4
        bedrooms_count: int4
        bath_count: float4
        year_joined: int4
        tax_assessed_value_total: int4
        tax_billed_amount: float4
        tax_exemption: varchar
        construction_type: varchar
        stories_count: int4
        status_owner_occupied_flag: int4
        pool: int4
        rooms_basement_area: int4
        parking_space_count: int4

    states:
      schema: public
      table: states
      srid: 3857
      geometry_column: geometry
      id_column: ~
      minzoom: 2
      maxzoom: 30
      properties:
        id: int4
        abbr: varchar
        name: varchar

    zip_codes:
      schema: public
      table: zip_codes
      srid: 3857
      geometry_column: geometry
      id_column: ~
      minzoom: 10
      maxzoom: 30
      properties:
        id: int4

    counties:
      schema: public
      table: counties
      srid: 3857
      geometry_column: geometry
      id_column: ~
      minzoom: 8
      maxzoom: 30
      properties:
        id: int4
        name: varchar
        name_long: varchar

    county_subdivisions:
      schema: public
      table: county_subdivisions
      srid: 3857
      geometry_column: geometry
      id_column: ~
      minzoom: 8
      maxzoom: 30
      properties:
        id: int4
        name: varchar
        name_long: varchar
```
