### ISSUE TITLE
`max_feature_count` is not respected in config file

### ISSUE THREAD

**Issue by kevinschaich** [urbica/martin#585]
I've tried several versions of the `max_feature_count` parameter in the configuration and can't get it to work. 

Abridged config:

```yaml
listen_addresses: '0.0.0.0:3002'

postgres:
  connection_string: postgresql://postgres:$POSTGRES_PASSWORD@$POSTGRES_HOST:$POSTGRES_PORT/$POSTGRES_DB

  # Limit the number of table geo features included in a tile. Unlimited by default.
  max_feature_count: 1
```

Rebuilt & restarted my docker container, and in Chrome I have disable cache enabled in the network tab. There's only ~4 tile requests getting submitted, so with that config, I should have about 4 points on the map. But I have **way more than 4**:

<img width="1485" alt="image" src="https://user-images.githubusercontent.com/9244728/221324046-eaf2289e-5172-48dd-b376-ef9851a02cfa.png">

I'm not using NGINX or any other type of caching, just Martin. Any suggestions?
