### ISSUE TITLE
Docker image for arm64 platform

### ISSUE THREAD

**Issue by IncidGeo** [urbica/martin#655]
Hi there,
I get a "no matching manifest for linux/arm64/v8 in the manifest list entries" message using main docker image.
Is there a arm compatible Docker image for Martin ?

Thanks,

**Comment by nyurik** [comment]
@IncidGeo hi, the #613 tried to add a docker image to the automated build process, but we are having major problems building Arm docker image using github actions -- such that I plan to revert that PR until we have a better solution.  I would love to add Arm Martin docker images, but we could really use some help to automate it in a reliable way.

It seems the docker images for different platforms need to somehow be combined together into a single package (?) before uploading them to the ghcr?

See also #603 and #505

**Comment by IncidGeo** [comment]
Thank you nyurik. So to date there is'nt even a non-perfect solution to dockerize martin in the development phase ?

**Comment by nyurik** [comment]
@IncidGeo define "non-perfect" :)  There is a simple solution - you can just build it yourself instead of relying on a public docker image.  If you have an arm64 machine somewhere, simply build the arm64.docker file on it, and use it.

**Comment by IncidGeo** [comment]
It's beyond my skills, but I'll look into it, thank you.

**Comment by nyurik** [comment]
it's actually pretty simple:
* login to your Arm machine
* `git clone --depth=1 https://github.com/maplibre/martin`
* `cd martin`
* `docker build -f arm64.Dockerfile -t mydockerimage .`
* `docker run --rm -it mydockerimage`  (use mydockerimage as if you downloaded it from the docker hub / ghcr)

**Comment by IncidGeo** [comment]
Thank you very much nyurik.
I've finnally succed to create a arm compatible docker image on a my private docker repository and pull it from my docker-compose.yml. It works.
• `docker tag mydockerimage dockerusername/nameofthedockerimage:test`
• `docker push dockerusername/nameofthedockerimage:test`
In the docker-compose.yml :
```
version: '3'

services:

  djangoapp:
    build:
        context: .
        dockerfile: config/dockerfiles/Dockerfile_django_python
    volumes:
      - .:/opt/services/djangoapp/src
      - static_volume:/opt/services/djangoapp/static  
      - media_volume:/opt/services/djangoapp/media  
    networks:
      - nginx_network
      - database1_network
    depends_on:
      - database1

  nginx:
    restart : always
    build:
        context: .
        dockerfile: config/dockerfiles/Dockerfile_nginx
    ports:
      - 80:80
    volumes:
      - static_volume:/opt/services/djangoapp/static 
      - media_volume:/opt/services/djangoapp/media   
    depends_on:
      - djangoapp
    networks:
      - nginx_network

  database1:
    restart : always
    build:
        context: .
        dockerfile: config/dockerfiles/Dockerfile_postgres
    ports:
      - 5432:5432
    env_file:
      - config/db/database1_env
    networks:
      - database1_network
    volumes:
      - database1_volume:/var/lib/postgresql/data

  martin:
    image: dockerusername/nameofthedockerimage:test
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgresql://postgresusername:password@database1/database1 
    depends_on:
      - database1

networks:
  nginx_network:
    driver: bridge
  database1_network:
    driver: bridge

volumes:
  database1_volume:
  static_volume:  
  media_volume: 

  ```
dockefile for postgres (as there is the same problem for arm machine and postgis) :

```
FROM postgres

RUN apt update
RUN apt install postgis -y
COPY ./config/db/db.sql /docker-entrypoint-initdb.d/
```
db.sql :
`CREATE EXTENSION postgis;`

Just need now to figure out how to set up Nginx, django, postgres, martin together in the yml or maybe in the nginx conf file because Martin can't connect to the database while django/Gunicorn can, but it's an other subject.

**Edit1** : It is working properly with the github "Using with Docker Compose" example :
```
version: '3'

services:
  martin:
    image: dockerusername/nameofthedockerimage:test
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db/db
    depends_on:
      - db

  db:
    build:
        context: .
        dockerfile: Dockerfile_postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - ./pg_data:/var/lib/postgresql/data
```
and 

```
FROM postgres

RUN apt update
RUN apt install postgis -y
COPY ./config/db/db.sql /docker-entrypoint-initdb.d/
```
db.sql :
`CREATE EXTENSION postgis;`

**Edit2:** Ok i'm such a nut, bridge were missing in the docker-compose.yml, now everything is working fine (i've change the db name and service nam for readability)
```
version: '3'

services:

  djangoapp:
    build:
        context: .
        dockerfile: config/dockerfiles/Dockerfile_django_python
    volumes:
      - .:/opt/services/djangoapp/src
      - static_volume:/opt/services/djangoapp/static  
      - media_volume:/opt/services/djangoapp/media  
    networks:
      - nginx_network
      - db_network
    depends_on:
      - db
      - martin

  nginx:
    restart : always
    build:
        context: .
        dockerfile: config/dockerfiles/Dockerfile_nginx
    ports:
      - 80:80
    volumes:
      - static_volume:/opt/services/djangoapp/static 
      - media_volume:/opt/services/djangoapp/media   
    depends_on:
      - djangoapp
    networks:
      - nginx_network

  db:
    restart: unless-stopped
    build:
        context: .
        dockerfile: config/dockerfiles/Dockerfile_postgres
    ports:
      - 5432:5432
    env_file:
      - config/db/db_env
    networks:
      - db_network
      - martin_network
    volumes:
      - db_volume:/var/lib/postgresql/data

  martin:
    image: dockerusername/nameofthedockerimage:test
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgresql://postgres:password@db/db 
    depends_on:
      - db
    networks:
      - db_network
      - martin_network
      - nginx_network


networks:
  nginx_network:
    driver: bridge
  db_network:
    driver: bridge
  martin_network:
    driver: bridge

volumes:
  db_volume:
  static_volume:  
  media_volume: 

```
