### ISSUE TITLE
Handle collisions of different json properties having the same structure

### ISSUE THREAD

**Issue by ArtOshchepkov** [urbica/martin#662]
# TLDR
Handle different properties of json type having the same structure. 

# Story
I count crime & health indicators compared to `country` and `states`.
I keep my data in json in PSQL like following:

```yaml
crime_indicator: jsonb =  {
 by_state: 42;
 by_country: 100500;
}
health_indicator: jsonb = {
 by_state: 22;
 by_country: 8;
}
```

My Martin's config describes both jsonb variables:
```yaml
properties:
      crime_indicator: jsonb
      health_indicator: jsonb
```

Requesting the tile, I got only one indicator in the feature:
```yaml
properties:
 by_state: 42
 by_country: 10050
```

Instead, I'd like to see both features:
```yaml
properties:
  crime_indicator_by_state: 42;
  crime_indicator_by_country: 8;
  health_indicator_by_state: 22;
  health_indicator_by_country: 8;
```
Or actual jsons

# My suggestions
1. Optionally add prefix to json values to avoid collisions.

# Other

may be connected to #550 #222

Thank you for your work!
