### ISSUE TITLE
Specifying an `id` column with `auto_publish`

### ISSUE THREAD

**Issue by nyurik** [urbica/martin#682]
Auto-discovered PG tables may have some columns that should be exposed as a feature ID rather than just being a regular feature property.  I propose to add an `id_column` param as shown below.

```yaml
postgres:
  connection_string: ${DATABASE_URL}
  auto_publish:
      tables:
        # Set a custom source ID based on the table name
        id_format: 'table.{schema}.{table}.{column}'
        # A table column to use as the feature ID
        # If a table has no column with this name, `id_column` will not be set for that table.
        # We could even allow a list of strings here - the first found column will be treated as a feature ID.
        id_column: 'id'
```

### Deliverables
  - [ ] allow `id_column` string param to specify the default id column if it exists.  If it does not exist, log an info message. If the column exists, but it is NOT an integer, log a warning.  If ID column is found, it will NOT be exported as a property, only as the ID.
  - [ ] Optional: possibly allow `id_column` to be a list of strings, so if a table has any of the specified columns, use it.
  - [ ] Optional: consider renaming `id_format` into `source_id_format`, with backwards compatibility

Discussed in https://github.com/maplibre/martin/discussions/680
