### ISSUE TITLE
How to create tiles form OSM Postgis DB

### ISSUE THREAD

**Issue by borys-spiridonov-yal** [urbica/martin#757]
What I have done so far is created postgis schema and imported the data with osmosis tool as described here:
https://wiki.openstreetmap.org/wiki/Osmosis/PostGIS_Setup#Create_and_Initialise_Database

Martin has successfully connected to the database and discovered some tables as sources. How do I determine what table I need to use to query the tiles? , because this step is not covered in Martin documentation. I have the following output form /catalog API:

```yaml
// 20230711102602
// https://martin-tiles.domain.io/catalog
[
  {
    "id": "addrfeat",
    "content_type": "application/x-protobuf",
    "description": "tiger.addrfeat.the_geom"
  },
  {
    "id": "bg",
    "content_type": "application/x-protobuf",
    "description": "tiger.bg.the_geom"
  },
  {
    "id": "county",
    "content_type": "application/x-protobuf",
    "description": "tiger.county.the_geom"
  },
  {
    "id": "cousub",
    "content_type": "application/x-protobuf",
    "description": "tiger.cousub.the_geom"
  },
  {
    "id": "edges",
    "content_type": "application/x-protobuf",
    "description": "tiger.edges.the_geom"
  },
  {
    "id": "faces",
    "content_type": "application/x-protobuf",
    "description": "tiger.faces.the_geom"
  },
  {
    "id": "nodes",
    "content_type": "application/x-protobuf",
    "description": "public.nodes.geom"
  },
  {
    "id": "place",
    "content_type": "application/x-protobuf",
    "description": "tiger.place.the_geom"
  },
  {
    "id": "state",
    "content_type": "application/x-protobuf",
    "description": "tiger.state.the_geom"
  },
  {
    "id": "tabblock",
    "content_type": "application/x-protobuf",
    "description": "tiger.tabblock.the_geom"
  },
  {
    "id": "tabblock20",
    "content_type": "application/x-protobuf",
    "description": "tiger.tabblock20.the_geom"
  },
  {
    "id": "tiles",
    "content_type": "application/x-protobuf",
    "content_encoding": "gzip",
    "name": "united_states_of_america.mbtiles",
    "description": "united_states_of_america.mbtiles"
  },
  {
    "id": "tract",
    "content_type": "application/x-protobuf",
    "description": "tiger.tract.the_geom"
  },
  {
    "id": "zcta5",
    "content_type": "application/x-protobuf",
    "description": "tiger.zcta5.the_geom"
  }
]
```

With mbtiles source everything is straightforward and Martin exposes the file as a single tile source, however with postgis, it isn't clear what tables to use.
