### ISSUE TITLE
Making changes to config.yaml on docker

### ISSUE THREAD

**Issue by everestas** [urbica/martin#788]
I am running Martin on Docker with Docker-compose file. I am trying to figure out how to make changes to config.yaml file while Martin is running. 

In order to retrieve config.yaml file I have come up with a hacky solution. I run this docker-compose.yaml file:
 ```yaml
version: '3'
services:
  martin:
    image: ghcr.io/maplibre/martin:v0.8.7
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL="url"
    command: --save-config /home/config.yaml
```

This save a config file in /home dir. Then I am able to run this command to retrieve it:

```
docker exec container_id cat /home/config.yaml
```

Now, I have a config.yaml file locally which I can edit and probably let Martin use with `command: --config /home/config.yaml` in Docker-compose.yaml.

Very hacky solution. Is there a better way to do it?
