### ISSUE TITLE
Specifying strid for a table for Docker-compose installation

### ISSUE THREAD

**Issue by everestas** [urbica/martin#789]
I am running Martin with docker-compose:
```yaml
version: '3'
services:
  martin:
    image: ghcr.io/maplibre/martin:v0.8.7
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL="url"
```

Martin in the log says:
```
martin-martin-1  | [2023-07-28T14:03:50Z INFO  martin] Starting Martin v0.8.7
martin-martin-1  | [2023-07-28T14:03:50Z INFO  martin] Config file is not specified, auto-detecting sources
martin-martin-1  | [2023-07-28T14:03:50Z INFO  martin::args::pg] Using env var DATABASE_URL to connect to PostgreSQL
martin-martin-1  | [2023-07-28T14:03:50Z INFO  martin::pg::pool] Connecting to "url"
martin-martin-1  | [2023-07-28T14:03:51Z WARN  martin::pg::table_source] Table public.daylight_buildings has no spatial index on 
martin-martin-1  | [2023-07-28T14:03:51Z WARN  martin::pg::table_source] Table public.daylight_buildings.geom has SRID=0, skipping. To use this table source, set default or specify this table SRID in the config file, or set the default SRID with  --default-srid=...
```

Is there a way to specify srid while running Martin on Docker-compose?
