### ISSUE TITLE
Set TileJSON layer metadata for function sources in config

### ISSUE THREAD

**Issue by nick-romano** [urbica/martin#822]
For full parity with table sources, it would be helpful to have metadata available for function sources within the tilejson response.

Some relevant issues:
- https://github.com/maplibre/martin/issues/749
- https://github.com/maplibre/martin/issues/277

**Comment by nick-romano** [comment]
seems like this could be difficult if the function accepts query params...

**Comment by nyurik** [comment]
We definitely need to be able to set various per-source settings in the config, especially settings that are not auto-discoverable from the source itself.  Let's sketch out some config structures first - my proposal is to allow direct tilejson modification:

```yaml
postgres:
  functions:
    my_func:
      tilejson:
        description: my magical tile source
        # Here goes any fields that should be set in the tilejson,
        # overriding anything that's already being set there automatically.
        # Note that setting field to `null`, e.g. `description: ~` should remove it from output.
```

Note that the above could be used for all other sources, not just Postgres functions (i.e. tables, mbtiles, pmtiles). Moreover, it could be allowed in the `auto_publish` section too.  In auto-publish, it could use the same placeholders as in the `source_id_format`, e.g. `{schema}, {table}, {column}`
