### ISSUE TITLE
Cloud Optimized GeoTIFF (COG) support

### ISSUE THREAD

**Issue by sharkAndshark** [urbica/martin#875]
Add support for [Cloud Optimized GeoTIFF (COG)](https://www.cogeo.org/).

## CLI
```shell
martin  /path/to/cogs/file.tif  /path/to/directory
```

## Conf file
```yaml
...
cogs:
  paths:
    # scan this whole dir, matching all *.tif files
    - /dir-path
    # specific cog file will be published as cog source
    - /path/to/file1.tif
  sources:
   # named source matching source name to a single file
    cog-src1:  /path/to/file.tif
```

It seems that the conf sections about PMTiles and MBTiles are very similar.  I don't know maybe we could merge them into a single section? 
```yaml
files:
  paths:
    - /dir1
    - /path/to/file1.ext
  sources:
    source1: /path/to/file.ext
```

Things to track:

- [x] Rgb/Rgba with 8 bits per sample
      done by #1590
- [x] Auto-discovery for both `*.tif` and `*.tiff` 
      done by #1635 
- [ ] Gray and 8 bits per sample
- [ ] Other combination of color-type and bits per sample
- [ ] Common compression method which [tiff crate](https://crates.io/crates/tiff) not supported. More research needs to do here.
  - [x] NONE
  - [x] PACKBITS
  - [x] Deflate
  - [X] LZW
  - [X] ModernJPEG
  - [x] ZSTD (since https://github.com/image-rs/image-tiff/pull/256)
  - [ ] LZMA
- [ ] Do not ignore sub-file which is mask, more research needs to do here
- [ ] Remote COG file like S3
