### ISSUE TITLE
Support PMTiles reading over HTTP

### ISSUE THREAD

**Issue by nyurik** [urbica/martin#884]
PMTiles is a web-optimized format, allowing the actual file to be read with HTTP range requests.  Supporting this use case instantly allows Martin to function as a lambda executable accessing PMTiles, but without any significant investment into devops or hosting large file.

In order to support this type of serving, PMTiles config should also allow `http` and `https` protocol:

```
# Publish PMTiles files
pmtiles:
  paths:
    # specific pmtiles file will be published as mypmtiles source
    # (use last portion of the URL without extension)
    - http://example.org/path/to/mypmtiles.pmtiles
  sources:
    # named source matching source name to a single file
    pm-src1: https://example.org/path/to/some_pmtiles.pmtiles
 ```

**Comment by sharkAndshark** [comment]
Is this in consideration also?
```shell
martin https://example.org/path/to/some_pmtiles.pmtiles
```

**Comment by sharkAndshark** [comment]
Before I go further, can this be a start? 
```rust
pub enum FileConfigEnum {
    Location(Location),
    Locations(Vec<Location>),
    Config(FileConfig),
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub enum Location {
    Path(PathBuf),
    Url(String),
}
```

**Comment by nyurik** [comment]
@sharkAndshark while it looks much better from the structure perspective, I think it will not be clear or easy to implement. If a user writes this config

```yaml
# Publish PMTiles files
pmtiles:
  paths:
    - /local/path/to/some/file.pmtiles
    - http://example.org/path/to/mypmtiles.pmtiles
  sources:
    pm-src1: https://example.org/path/to/some_pmtiles.pmtiles
    pm-src2: /local/path/to/some/other/file.pmtiles
```

In both cases, it is just a string - so something else must test the prefix.  I would recommend not changing the enums, but instead just add a test for `startswith("http://") || startswith("https://")`, and treat them differently.  You may have a minor issue with validating that PathBuf is safe to convert to a String, but its a minor thing.  Worst case - you can convert them all to Strings instead.
