### ISSUE TITLE
The --config and the connection parameters cannot be used together

### ISSUE THREAD

**Issue by epam-vkerkhoff** [urbica/martin#938]
Hello, 

I get the message 

The --config and the connection parameters cannot be used together

when starting Martin in a docker container like this: 

```
docker run -v ./conf.yml:/conf.yml -it ghcr.io/maplibre/martin:v0.9.2  martin -c /conf.yml
Unable to find image 'ghcr.io/maplibre/martin:v0.9.2' locally
v0.9.2: Pulling from maplibre/martin
96526aa774ef: Already exists 
b9af053ced66: Pull complete 
Digest: sha256:67b7d0ff9bf6e80c0fc4df7c6eea2cf7f01affc65338519a2ab179289a8be5b6
Status: Downloaded newer image for ghcr.io/maplibre/martin:v0.9.2
[2023-10-12T10:11:58Z INFO  martin] Starting Martin v0.9.1
[2023-10-12T10:11:58Z INFO  martin] Using /conf.yml
[2023-10-12T10:11:58Z ERROR martin] The --config and the connection parameters cannot be used together

```

Contents of conf.yml: (first lines): 

```
# The socket address to bind [default: 0.0.0.0:3000]
listen_addresses: '0.0.0.0:5000'

postgres:
  # Database connection string
  connection_string: 'postgres://bbnavihub:thesecretpass@172.17.0.3/bbnavihub'

  # disable automatic discovery of tables and functions
  auto_publish: false

  # Associative arrays of table sources
  table_sources:
    public.poi_coords:
```

No, there is no ENV variable with DATABASE_URL anywhere. I made sure. Happens on any host. PostGIS is up and running, other apps can access it without issues. 

Thanks and best regards,

**Comment by epam-vkerkhoff** [comment]
Sorry, I just saw my mistake. 

I should use `docker run -v ./conf.yml:/conf.yml -it ghcr.io/maplibre/martin:v0.9.2 -c /conf.yml`

Instead of `docker run -v ./conf.yml:/conf.yml -it ghcr.io/maplibre/martin:v0.9.2  martin -c /conf.yml`

**Comment by nyurik** [comment]
@epam-vkerkhoff no problem, glad you figured it out. What docs did you use initially? Maybe we should update the documentation or the book accordingly?

**Comment by nyurik** [comment]
I added a better error reporting that explains which params should be removed.

**Comment by george-silva** [comment]
Sorry about reliving this issue here. I've tried a similar approach configuring docker compose and had to multiple tries. Did not know you could have a fixed command passing only part of the command.

this is what worked for us. Notice that `command` does not require the full command like `martin -c your_config_file`

```
  martin:
    image: ghcr.io/maplibre/martin:v0.13.0
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db/postgres
    command: --config /usr/src/app/martin.yaml 
    volumes:
      - .:/usr/src/app
```
