### ISSUE TITLE
Allow fine-tuning of buffer settings according to the zoom level

### ISSUE THREAD

**Issue by sharkAndshark** [urbica/martin#987]
To fine tune the buffer settings, allow something like:
```yaml
# The buffer settings can be either fixed or vary based on the zoom level
buffer:
  z0-z4: 0
  z5-z14: 64
# Fixed
#buffer: 64
```
